name: Run Wingman Tests

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

env:
    PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    
jobs:
  tests:
    name: Wingman Hardhat Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm ci

      - name: Compile contracts
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test
